name = "V"
grammar = "v"
path_suffixes = ["v", "vv", "vsh"]
line_comments = ["//"]
block_comment = ["/*", "*/"]
autoclose_before = "=}]):\",\n\t "

language_servers = ["v-analyzer"]

word_characters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "_"]

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
  { start = "`", end = "`", close = true, newline = false },
]
debuggers = ["LLDB", "GDB"]
# V uses tabs for indentation
indent = { tab_size = 4, unit = "\t" }
